spring.application.name=auth-service
server.port=8081

# ===============================
# MySQL Database
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/auth_db
spring.datasource.username=${MYSQL_USERNAME}
spring.datasource.password=${MYSQL_PASSWORD}

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Sendlib Email
# ===============================
sendlib.api-url=https://sendlib.samueltuoyo.com/api/send
sendlib.api-key=${SENDLIB_API_KEY}
sendlib.from-email=${SENDLIB_FROM_EMAIL}